export interface Product {
    id: number,
    categoryId: number,
    name: string,
    price: number,
    description: string,
    companyId: number,
    createdAt: Date,
    updatedAt: Date,
    frame: string,
    mounted: string,
    screen: string,
    buttons: string,
    weight: number,
    backlight: string,
    type: string,
    foam: string,
    mum: string,
    smartpause: string,
    turbopressure: string,
    imagePath: string,
}
